[package]
name = "snippets-app"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

time = { version = "0.3", features = ["serde", "parsing", "formatting"] }
rusqlite = { version = "0.31", features = ["bundled"] }
anyhow = "1"